ALTER TABLE users
ADD COLUMN phone_new VARCHAR(15),
ALGORITHM=INPLACE,
LOCK=NONE;

UPDATE users
SET phone_new = CAST(phone AS CHAR)
WHERE phone_new IS NULL;

ALTER TABLE users
DROP COLUMN phone,
CHANGE COLUMN phone_new phone VARCHAR(15),
ALGORITHM=INPLACE,
LOCK=NONE;